### PR TITLE
fix for deprecated `get_ticklabel_extents`

### LINKED ISSUE #34: label length
I'm getting an `AttributeError`.  The traceback is
```
File ~/micromamba/envs/e2/lib/python3.11/site-packages/pygtc/pygtc.py:935, in plotGTC(chains, **kwargs)
    932 # x labels
    933 # Get label length of the bottom row
    934 for i in range(len(axH)):
--> 935     bboxTickLabel = (axH[i].xaxis.get_ticklabel_extents(renderer)[0]
    936                      .get_points())
    937     bboxSize[i] = bboxTickLabel[1, 1]-bboxTickLabel[0, 1]
    938     panelWidth = (axH[i].get_window_extent()
    939                   .transformed(fig.dpi_scale_trans.inverted()).width)

AttributeError: 'XAxis' object has no attribute 'get_ticklabel_extents'
```

This attribute seems to have been [deprecated](https://matplotlib.org/3.7.0/api/_as_gen/matplotlib.axis.Axis.get_ticklabel_extents.html) as of `matplotlib 3.6`. Do you know a quick workaround?

### PR DESCRIPTION
**Pull request by samueldmcdermott**
this closes #34 by changing deprecated `get_ticklabel_extents` to `get_tightbbox`

### CODE REVIEW

**Comment by FaustinCarter** [comment]
I ran the test images locally with python=3.8 and matplotlib 3.2 and the new code looks good for all the images _except_ those that set param names (in other words, anything that includes an axis label). Here's  two images to show the general idea, but basically the labels get pushed waaaay out.


# New Code:
result

# Old Code:
baseline

**Comment by FaustinCarter** [comment]
With python 3.11 and matplotlib 3.7, all the tests pass (identical!) except anything with param labels, since the labels get pushed waaay out. @samueldmcdermott Want to take a stab at seeing if you can get the parameter labels pulled back in near the ticks? I'm happy to generate new test images from the updated code for the four tests that are failing as long as the images generated pass the spirit of the test.

**Comment by samueldmcdermott** [comment]
hm, sorry, I just spent a little while on this and couldn't figure it out in a nice way. I'm not entirely sure what the previous division between `bboxTickLabel` and `panelWidth` / `panelHeight` was supposed to accomplish, and I'm also not sure why `bboxSize` was a vector but `panelWidth` / `panelHeight` were not. I can try to scrap that section and find a new way to get the correct spacing, but no guarantees...

**Comment by samueldmcdermott** [comment]
is there a reason not to rely on the builtin `fig.align_xlabels(axH)` and `fig.align_ylabels(axV)`? Replacing the whole block after line 915 with those two commands seems to work for me. I will push the change to my fork and you can see if that works for you. (But also feel free to give me direct feedback if that's not desirable.)

**Comment by FaustinCarter** [comment]
> is there a reason not to rely on the builtin `fig.align_xlabels(axH)` and `fig.align_ylabels(axV)`? Replacing the whole block after line 915 with those two commands seems to work for me. I will push the change to my fork and you can see if that works for you. (But also feel free to give me direct feedback if that's not desirable.)

Wow, those look great! I can barely tell the difference between our base images and the ones generated by those methods! To answer your question, when we wrote this, we were dealing with matplotlib 1.5, which did not have very sensible defaults, nor did it have very many helper methods for things like this.

I did some sleuthing and it looks like these new methods were added in matplotlib 2.2. So as long as we update the minimum version pin for matplotlib, this is a great solution. Thanks for doing all the hard work :)

If you are willing to give me push access to this repo/branch, I'll update your fix with some release notes and a version bump, fix all the version pinning, and any fixes need to make sure docs build and example notebooks run. Then we can merge it in and I'll cut a new release to both pypi and conda-forge.

**Comment by samueldmcdermott** [comment]
ok, thanks for explaining -- it seemed probable there was a simple explanation like that, but I didn't want to assume. I'll give you push access now

**Comment by FaustinCarter** [comment]
Thanks @samueldmcdermott, great contribution!

**Comment by samueldmcdermott** [comment]
glad to hear, happy it helped, and thanks for making and maintaining such an easy-to-use tool!

**Pull request merged**
