### PR TITLE
first try at automatic build and test

### PR DESCRIPTION
**Pull request by FaustinCarter**
Here's a file to try and automatically use github actions to build and test pygtc. Let's see if we can get it working!

### CODE REVIEW

**Comment by FaustinCarter** [comment]
OK, so all the tests are running now (except on python 2, where there is still some issue with backends maybe?). Also not on osx, since there is some issue with how python has to be installed. Will work on that later.

Overall, test images look good, but they aren't coming out quite the same size. Probably some small change matplotlib made. Who knows. We may want to just generate new test images for matplotlib 3 and move on.

**Comment by SebastianBocquet** [comment]
Nice work! FWIW the tests pass on my mac (running python 3.6.9 and matplotlib 3.1.1) but I do get warnings about open figures.
I think for now it's ok if python 2 automated tests fail. The python 2 user loves high-risk activities so let's give them the adrenaline they're after!
Let's fix the merge conflict and move on!

**Comment by FaustinCarter** [comment]
Well, I just ran the tests on my machine with Python 3.6.9 and Matplotlib 3.1.1 and all my tests failed. My best guess is that this is a font issue. I think there is an option with pytest-mpl to ignore text labels. We should try and figure out what font you are using and maybe I can install that and run tests with that. If that works, then we can regenerate test images using whatever default font is guaranteed to be on the CI servers...

**Comment by FaustinCarter** [comment]
So I did a bit of testing with various things, and so far I've found that tests pass on my local machine with freetype 2.9.1, but fail on my local machine with 2.10.1. This is because of some very slight differences in how the fonts are getting rendered.

**Comment by FaustinCarter** [comment]
Ok, so tests are passing now, but only on Windows, and only on python >= 3.6. I think that is good enough. We've only ever advertised python 3 support for 3.6 and later and 2.7 is dead, so we are not under any onus to guarantee pixel perfect images there anymore (and besides, pytest doesn't work on 2.7). I'm using a conda environment to pin freetype to 2.9.1 for the auto-testing on github workflows. 

I've also tested the read-the-docs building and it is working well too! So we are pretty much good to go, I think! If we merge this an and fix whatever read-the-docs needs us to do for auto-building the docs on commit, then we will be good for a new release.

@SebastianBocquet If you can pull down this branch and run tests on your own, and maybe make sure some research code still generates good plots, then I think we can call it a day!

**Comment by SebastianBocquet** [comment]
Alright, the tests pass on my laptop and on my favorite linux computing cluster.
I'm pretty sure the webhook for readthedocs is such that it will re-compile the docs upon push to master.

**Comment by SebastianBocquet** [comment]
Seems like something funny happened when changing the base branch after initial commits. Anyway, conflicts are resolved, merging now!

**Pull request merged**
