### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by SebastianBocquet**
Some fixes and improvements:
  * Update deprecated `normed` keyword for matplotlib and numpy histograms to `density` #13 
  * Add version number to package itself
  * Add tests to the distribution #17

### CODE REVIEW

**Comment by FaustinCarter** [comment]
There is a potential issue with the switch from normed to density for histogram kwargs. Namely, if we are going to make that change, then we are requiring that matplotlib >= 2.1.0 and numpy >= 1.7.1. I think this is a pretty reasonable requirement, but before this switch, we were still compatible all the way back to 1.5.3.

Another benefit to requiring matplotlib >=2.1.0 is we can get rid of this hack, and clean up the code base a little:
https://github.com/SebastianBocquet/pygtc/blob/6765e2f7bfdd9fe6edd4a9f5a84da56d5d91eda4/pygtc/pygtc.py#L798-L810

Let me know your thoughts, and I'll update the changelog and requirements and documentation as appropriate. The alternate is to do some matplotlib version checking for earlier versions, and pass normed for matplotlib < 2.1.0.

**Comment by SebastianBocquet** [comment]
As far as numpy 1.7.1 is concerned, I'm fine with dropping support. It was released just over 7 years ago.

However, matplotlib 2.1.0 was released less than 3 years ago so I don't think we should drop support (yet). Or should we simply force people to update their stuff? (Thinking about a collaborator who is proud that he hasn't updated his python environment in over 4 years...)

**Comment by FaustinCarter** [comment]
OK, In that case, we should continue support for the next release, but when we move forward with the python3-only version, we can drop support for normed there. I can code up this fix tonight... Or you can if you are bored.

**Comment by FaustinCarter** [comment]
If all the tests pass, I think we are ready to merge this. Then we can do a version bump and deploy. We should probably figure out how to auto-deploy... I'll look into that.

**Comment by FaustinCarter** [comment]
Also, we should decide whether to package the legacy_baseline images as well as the baseline images. It's only an extra 3 MB or so, but it does nearly double the package size...

**Comment by SebastianBocquet** [comment]
I would suggest that if we allow for the legacy_baseline tests then we should package them. A test that's a pain to execute is a poor/useless test I think. I'm willing to pay 3MB for that.

**Pull request merged**
